import Head from 'next/head';
import { PageViewMessageBoard } from '@/components/PageViewMessageBoard';
import { api } from '@/api/index';
import { MessageBoardItem } from '@/entityTypes/messageBoard';

export async function getServerSideProps() {
  const messageFromServer = await api.messageBoard.getMessageList();

  return { props: { messageFromServer } };
}

interface HomeProps {
  messageFromServer: MessageBoardItem[];
}

export default function Home({ messageFromServer }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageViewMessageBoard messageFromServer={messageFromServer} />
    </>
  );
}
