import Head from 'next/head';
import { PageViewMessageBoard } from '@/components/PageViewMessageBoard';
import { api } from '@/api/index';
import { MessageBoardItem } from '@/entityTypes/messageBoard';
import { ErrorView } from '@/components/ErrorView';

export async function getServerSideProps() {
  let messageFromServer = null;
  try {
    messageFromServer = await api.messageBoard.fetchMessageList();
  } catch (e) {
    messageFromServer = null;
  }

  return { props: { messageFromServer } };
}

interface HomeProps {
  messageFromServer: MessageBoardItem[] | null;
}

export default function Home({ messageFromServer }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {messageFromServer && (
        <PageViewMessageBoard messageFromServer={messageFromServer} />
      )}

      {messageFromServer === null && (
        <ErrorView
          error={{
            message:
              'ошибка обращения к АПИ для получения предварительных данных',
          }}
        />
      )}
    </>
  );
}
